name: vape_simulator
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.6.1
  audioplayers: ^3.0.1
  shared_preferences: ^2.0.18
  provider: ^6.0.5
  volume_control: ^0.1.5
  easy_service_manager: ^1.2.3
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

#  flutter_launcher_icons: ^0.12.0
#  flutter_app_name: ^0.1.1
###  flutter pub run flutter_app_name
#flutter_app_name:
#  name: "Vape Simulation"


#  flutter pub run flutter_launcher_icons:main
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon.jpg"

#  flutter pub run flutter_native_splash:create
#flutter_native_splash:
#  color: "#FFFFFF"
#  android: true
#  ios: true
#  image: 'assets/splash.jpg'
#  android_gravity: fill
#  ios_content: fill


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/backgrounds/
    - assets/fonts/

  fonts:
    - family: MachineFont
      fonts:
        - asset: assets/fonts/MachineFont.ttf